In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("sample_data/california_housing_test.csv")

In [3]:
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       -122.05     37.37                27.0       3885.0           661.0   
1       -118.30     34.26                43.0       1510.0           310.0   
2       -117.81     33.78                27.0       3589.0           507.0   
3       -118.36     33.82                28.0         67.0            15.0   
4       -119.67     36.33                19.0       1241.0           244.0   
...         ...       ...                 ...          ...             ...   
2995    -119.86     34.42                23.0       1450.0           642.0   
2996    -118.14     34.06                27.0       5257.0          1082.0   
2997    -119.70     36.30                10.0        956.0           201.0   
2998    -117.12     34.10                40.0         96.0            14.0   
2999    -119.63     34.42                42.0       1765.0           263.0   

      population  households  median_income  median_house_value  
0         1537.0       606.0         6.6085            344700.0  
1          809.0       277.0         3.5990            176500.0  
2         1484.0       495.0         5.7934            270500.0  
3           49.0        11.0         6.1359            330000.0  
4          850.0       237.0         2.9375             81700.0  
...          ...         ...            ...                 ...  
2995      1258.0       607.0         1.1790            225000.0  
2996      3496.0      1036.0         3.3906            237200.0  
2997       693.0       220.0         2.2895             62000.0  
2998        46.0        14.0         3.2708            162500.0  
2999       753.0       260.0         8.5608            500001.0  

[3000 rows x 9 columns]

In [ ]:
df.isna().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

### multiple variable regression (checking how it works).

In [ ]:
Y=df["median_house_value"]

In [ ]:
Y

0         66900.0
1         80100.0
2         85700.0
3         73400.0
4         65500.0
           ...   
16995    111400.0
16996     79000.0
16997    103600.0
16998     85800.0
16999     94600.0
Name: median_house_value, Length: 17000, dtype: float64

In [ ]:
Y=np.array(Y)

In [ ]:
Y

array([ 66900.,  80100.,  85700., ..., 103600.,  85800.,  94600.])

In [ ]:
Y.reshape(1,len(Y))

array([[ 66900.,  80100.,  85700., ..., 103600.,  85800.,  94600.]])

In [ ]:
Y.shape

(17000,)

In [6]:
X=df.drop("median_house_value",axis=1)
X

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       -122.05     37.37                27.0       3885.0           661.0   
1       -118.30     34.26                43.0       1510.0           310.0   
2       -117.81     33.78                27.0       3589.0           507.0   
3       -118.36     33.82                28.0         67.0            15.0   
4       -119.67     36.33                19.0       1241.0           244.0   
...         ...       ...                 ...          ...             ...   
2995    -119.86     34.42                23.0       1450.0           642.0   
2996    -118.14     34.06                27.0       5257.0          1082.0   
2997    -119.70     36.30                10.0        956.0           201.0   
2998    -117.12     34.10                40.0         96.0            14.0   
2999    -119.63     34.42                42.0       1765.0           263.0   

      population  households  median_income  
0         1537.0       606.0         6.6085  
1          809.0       277.0         3.5990  
2         1484.0       495.0         5.7934  
3           49.0        11.0         6.1359  
4          850.0       237.0         2.9375  
...          ...         ...            ...  
2995      1258.0       607.0         1.1790  
2996      3496.0      1036.0         3.3906  
2997       693.0       220.0         2.2895  
2998        46.0        14.0         3.2708  
2999       753.0       260.0         8.5608  

[3000 rows x 8 columns]

In [ ]:
X=np.array(X)
X.shape

(17000, 8)

In [7]:
W=np.random.rand(1,X.shape[1])
W

array([[0.48578685, 0.24621428, 0.4493866 , 0.81433153, 0.43892144,
        0.01908921, 0.71963215, 0.81821212]])

In [ ]:
b=np.random.rand(1,1)
b.shape

(1, 1)

In [ ]:
Y_hat=np.dot(W,X.T)+b
Y_hat

array([[2411.81837078, 3289.98594639,  367.75465175, ..., 1286.54484751,
        1325.14408873,  806.04731513]])

In [ ]:
Y_hat.shape

(1, 17000)

In [ ]:
def loss(Y,Y_hat):
    return np.sum((Y-Y_hat)**2)/(2*len(Y))

In [ ]:
X.shape

(17000, 8)

In [ ]:
(Y_hat-Y).shape

(1, 17000)

In [ ]:
slope_arr=(np.matmul((Y_hat-Y),X))/len(Y)
slope_arr.shape

(1, 8)

In [ ]:
slope_arr

array([[ 2.46357371e+07, -7.30163377e+06, -6.04839581e+06,
        -5.75440371e+08, -1.12906261e+08, -2.89649996e+08,
        -1.05563322e+08, -9.52865903e+05]])

In [ ]:
W

array([[0.22735218, 0.30638713, 0.58506824, 0.14657303, 0.93175294,
        0.06550347, 0.70440846, 0.40581975]])

In [ ]:
W=W-0.01*slope_arr
W

array([[-246357.14404407,   73016.64406735,   60484.54314227,
        5754403.86042741, 1129063.54507333, 2896500.02120367,
        1055633.92661466,    9529.0648472 ]])

In [ ]:
def dldb(Y,Y_hat):
    return np.sum(Y_hat-Y)/len(Y)

In [ ]:
dldb(Y,Y_hat)

np.float64(-205961.10686190135)

### Implementation of multiple variable regression.

In [ ]:
#define a function to get the no of input varible and no of target variable.

def n_x_y(X,Y):#should pass dataset of form m*n where m is no of instances n is no of vaiables
    n_x=X.shape[1]
    n_y=Y.shape[1]
    return n_x,n_y

In [ ]:
#initialize model parameters W and b

def init_params(n_x,n_y):
    W=np.random.randn(n_y, n_x)*0.01 #W shape ny*nx
    b=np.random.randn(n_y,1) #b shape n_y*1
    return W,b


In [ ]:
#forward propagation

def forward_prop(X,W,b):
    y_hat=np.matmul(W,X.T)+b #gives yhat in the shape ny*m
    return y_hat.T #m*ny

In [ ]:
#Computing cost function.
def cost(Y,Y_hat):
    return np.sum((Y_hat-Y)**2)/(2*(Y.shape[0]))

In [ ]:
#update parameters
def update_param(Y_hat,Y,X,W,b,learning_rate):
    slope_arr= (np.matmul((Y_hat-Y).T,X))/len(Y)
    W=W-learning_rate*slope_arr
    b = b - learning_rate * np.mean(Y_hat - Y, axis=0).reshape(-1, 1)
    return W,b

In [ ]:
#develop a perceptron

def perceptron(X,Y,learning_rate,iterations):
    n_x,n_y= n_x_y(X,Y) #Get no of x and y
    W,b=init_params(n_x,n_y)# Get W and b
    for i in range(iterations):
        Y_hat=forward_prop(X,W,b) #Get Y_hat m*n_y
        loss=cost(Y,Y_hat)
        if (i%100==0):
            print(f"loss at iteration {i} is {loss}")
        W,b=update_param(Y_hat,Y,X,W,b,learning_rate)

    return W,b

In [ ]:
def predict(X,Y,X_pred,learning_rate,iterations):
    #normalizing data
    x_mean=np.mean(X,axis=0)
    x_std=np.std(X,axis=0)
    X=(X-x_mean)/x_std

    y_mean=np.mean(Y,axis=0)
    y_std=np.std(Y,axis=0)
    Y=(Y-y_mean)/y_std

    X_pred=(X_pred-x_mean)/x_std

    #calling perceptron
    W,b=perceptron(X,Y,learning_rate,iterations)

    #predicting
    Y_pred=np.matmul(W,X_pred.T)+b
    Y_pred=Y_pred.T
    #denormalizing
    Y_pred=Y_pred*y_std+y_mean

    return Y_pred


In [ ]:
X.shape

(17000, 8)

In [ ]:
Y=Y.reshape(len(Y),1)

In [ ]:
Y.shape

(17000, 1)

In [8]:
df_2=pd.read_csv("sample_data/california_housing_test.csv")

In [10]:
X_pred=df_2.drop("median_house_value",axis=1)
X_pred=np.array(X_pred)
X_pred.shape

(3000, 8)

In [ ]:
Y_actual=df_2["median_house_value"]
Y_actual=np.array(Y_actual)
Y_actual=Y_actual.reshape(len(Y_actual),1)
Y_actual.shape

(3000, 1)

In [ ]:
y_pred=predict(X,Y,X_pred,learning_rate=0.1,iterations=10000)
y_pred

loss at iteration 0 is 2.091519379881261
loss at iteration 100 is 0.19109831365552374
loss at iteration 200 is 0.1860943080543791
loss at iteration 300 is 0.183807234947595
loss at iteration 400 is 0.1824730314270961
loss at iteration 500 is 0.18160734096684872
loss at iteration 600 is 0.18100903756087428
loss at iteration 700 is 0.18057963002590482
loss at iteration 800 is 0.1802647510044856
loss at iteration 900 is 0.18003111985022774
loss at iteration 1000 is 0.17985667432045854
loss at iteration 1100 is 0.17972598453020946
loss at iteration 1200 is 0.17962790280806515
loss at iteration 1300 is 0.17955422519747932
loss at iteration 1400 is 0.1794988528505551
loss at iteration 1500 is 0.17945722728611788
loss at iteration 1600 is 0.17942593158101627
loss at iteration 1700 is 0.17940240063734397
loss at iteration 1800 is 0.1793847073055053
loss at iteration 1900 is 0.17937140312613525
loss at iteration 2000 is 0.17936139919163888
loss at iteration 2100 is 0.17935387680203302
loss at i

array([[352812.31418028],
       [212717.70180886],
       [272344.6937396 ],
       ...,
       [ 88220.57936931],
       [146374.67122068],
       [456779.61732169]])

In [ ]:
np.mean((Y_actual-y_pred)**2,axis=0)**0.5

array([69765.36042571])

In [ ]:
y_pred.shape

(3000, 1)

In [ ]:
Y_actual.shape

(3000, 1)

In [ ]:
np.random.randn()

2.3701186105483187

### Trying out for new dataset

In [ ]:
train_df=pd.read_csv("train_dataset.csv")
#test_df=pd.read_csv("test_dataset.csv")

In [ ]:
train_df

feature_1  feature_2  feature_3  feature_4  feature_5     target
0     0.781823  -1.236951  -1.320457   0.521942   0.296985   3.853510
1    -1.962626   0.349650  -1.564803   0.095344  -0.263448  -5.900605
2    -1.284584   0.977816  -2.105647   1.153590   1.386349  -3.134005
3    -0.351921  -0.769996  -1.296117  -0.456121   0.181427  -2.392503
4     0.278349  -0.509213  -0.846360  -0.584908  -0.478759  -1.134462
..         ...        ...        ...        ...        ...        ...
795   0.638592  -1.661520  -0.066080  -1.211016  -0.651836   0.006212
796  -1.170113  -1.801980   0.541463   0.759155  -0.576510   2.440976
797  -0.423599  -1.365617  -0.974122   0.703428  -1.307370   2.759099
798   2.089539  -1.607661   0.184741   2.023606   0.006800  13.509314
799   0.270457  -0.050238  -0.238948  -0.907564  -0.576771  -1.954960

[800 rows x 6 columns]

In [ ]:
train_df["target"].mean()

np.float64(-0.023277417096734608)

In [ ]:
test_df=pd.read_csv("test_dataset.csv")

In [ ]:
test_df

feature_1  feature_2  feature_3  feature_4  feature_5    target
0    -0.184525  -0.604745  -2.205566   0.897066   1.274875  0.577241
1    -0.850535   2.485190   0.264775   1.275391  -0.151714 -0.725975
2     1.065172   1.452617  -0.916321  -0.836921  -0.140375 -2.303698
3     0.338553  -0.937926   0.216625  -1.025753   1.100821 -1.590529
4    -0.819258  -0.476221   0.874389   0.262561   0.193590 -0.112381
..         ...        ...        ...        ...        ...       ...
195  -0.694713  -0.409282  -0.524088   0.152355  -0.822420 -0.801933
196   1.317115  -0.118069  -2.121855  -0.607822   1.296995 -0.770142
197   1.683928  -0.458884   1.078681  -0.038508  -0.172627  5.487776
198   0.321593   1.754933   0.018402   0.225264   0.692723 -0.925942
199  -0.898415   0.491919  -1.320233   1.831459   1.179440  1.228720

[200 rows x 6 columns]

In [ ]:
X=train_df.drop("target",axis=1)
Y=train_df["target"]

In [ ]:
X=np.array(X)
Y=np.array(Y)

In [ ]:
Y_actual=np.array(test_df["target"])
Y_actual.shape

(200,)

In [ ]:
Y.shape

(800,)

In [ ]:
X_pred=test_df.drop("target",axis=1)
X_pred=np.array(X_pred)
X_pred.shape

(200, 5)

In [ ]:
Y=Y.reshape(len(Y),1)
Y.shape

(800, 1)

In [ ]:
y_pred=predict(X,Y,X_pred,learning_rate=0.1,iterations=10000)
y_pred.shape

loss at iteration 0 is 0.9263324854598737
loss at iteration 100 is 0.00027542382687208004
loss at iteration 200 is 0.0002754231849109423
loss at iteration 300 is 0.0002754231849109412
loss at iteration 400 is 0.0002754231849109413
loss at iteration 500 is 0.0002754231849109413
loss at iteration 600 is 0.0002754231849109413
loss at iteration 700 is 0.0002754231849109413
loss at iteration 800 is 0.0002754231849109413
loss at iteration 900 is 0.0002754231849109413
loss at iteration 1000 is 0.0002754231849109413
loss at iteration 1100 is 0.0002754231849109413
loss at iteration 1200 is 0.0002754231849109413
loss at iteration 1300 is 0.0002754231849109413
loss at iteration 1400 is 0.0002754231849109413
loss at iteration 1500 is 0.0002754231849109413
loss at iteration 1600 is 0.0002754231849109413
loss at iteration 1700 is 0.0002754231849109413
loss at iteration 1800 is 0.0002754231849109413
loss at iteration 1900 is 0.0002754231849109413
loss at iteration 2000 is 0.0002754231849109413
loss a

(200, 1)

In [ ]:
(np.mean((Y_actual-y_pred)**2))**0.5

np.float64(5.5520571609303015)

### Multi target

In [ ]:
train_df=pd.read_csv("train_dataset_multi_target.csv")
test_df=pd.read_csv("test_dataset_multi_target.csv")

In [ ]:
test_df

feature_1  feature_2  feature_3  feature_4  feature_5  target_1  \
0    -0.184525  -0.604745  -2.205566   0.897066   1.274875  0.577241   
1    -0.850535   2.485190   0.264775   1.275391  -0.151714 -0.725975   
2     1.065172   1.452617  -0.916321  -0.836921  -0.140375 -2.303698   
3     0.338553  -0.937926   0.216625  -1.025753   1.100821 -1.590529   
4    -0.819258  -0.476221   0.874389   0.262561   0.193590 -0.112381   
..         ...        ...        ...        ...        ...       ...   
195  -0.694713  -0.409282  -0.524088   0.152355  -0.822420 -0.801933   
196   1.317115  -0.118069  -2.121855  -0.607822   1.296995 -0.770142   
197   1.683928  -0.458884   1.078681  -0.038508  -0.172627  5.487776   
198   0.321593   1.754933   0.018402   0.225264   0.692723 -0.925942   
199  -0.898415   0.491919  -1.320233   1.831459   1.179440  1.228720   

     target_2  target_3  
0    1.870451 -5.756786  
1    5.835265  4.121169  
2    3.143276  0.847742  
3   -2.814003  0.772752  
4   -1.941684  1.397501  
..        ...       ...  
195 -1.208384 -2.622380  
196  1.999315 -3.527116  
197 -0.104796  0.461250  
198  4.583956  3.397596  
199  3.976950 -2.283941  

[200 rows x 8 columns]

In [ ]:
X=np.array(train_df.drop(["target_1","target_2","target_3"],axis=1))
Y=np.array(train_df[["target_1","target_2","target_3"]])

In [ ]:
Y.shape

(800, 3)

In [ ]:
X.shape

(800, 5)

In [ ]:
X_pred=test_df.drop(["target_1","target_2","target_3"],axis=1)
X_pred=np.array(X_pred)
X_pred.shape

(200, 5)

In [ ]:
y_pred=predict(X,Y,X_pred,learning_rate=0.1,iterations=10000)
y_pred.shape

loss at iteration 0 is 4.152555987314728
loss at iteration 100 is 0.0015342801881531273
loss at iteration 200 is 0.0015342758627852765
loss at iteration 300 is 0.0015342758627852672
loss at iteration 400 is 0.0015342758627852667
loss at iteration 500 is 0.0015342758627852667
loss at iteration 600 is 0.0015342758627852667
loss at iteration 700 is 0.0015342758627852667
loss at iteration 800 is 0.0015342758627852667
loss at iteration 900 is 0.0015342758627852667
loss at iteration 1000 is 0.0015342758627852667
loss at iteration 1100 is 0.0015342758627852667
loss at iteration 1200 is 0.0015342758627852667
loss at iteration 1300 is 0.0015342758627852667
loss at iteration 1400 is 0.0015342758627852667
loss at iteration 1500 is 0.0015342758627852667
loss at iteration 1600 is 0.0015342758627852667
loss at iteration 1700 is 0.0015342758627852667
loss at iteration 1800 is 0.0015342758627852667
loss at iteration 1900 is 0.0015342758627852667
loss at iteration 2000 is 0.0015342758627852667
loss at 

(200, 3)

In [ ]:
Y_actual=np.array(test_df[["target_1","target_2","target_3"]])
Y_actual.shape

(200, 3)

In [ ]:
(np.mean((Y_actual-y_pred)**2,axis=0))**0.5

array([0.0987366 , 0.09380713, 0.10113082])